package builder

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/jurajpiar/devkit/internal/config"
	"github.com/jurajpiar/devkit/internal/detector"
)

// Builder handles container image building
type Builder struct {
	config    *config.Config
	detection *detector.DetectionResult
}

// New creates a new Builder
func New(cfg *config.Config, detection *detector.DetectionResult) *Builder {
	return &Builder{
		config:    cfg,
		detection: detection,
	}
}

// ContainerfileTemplate is the template for generating Containerfiles
const ContainerfileTemplate = `# Generated by devkit
ARG BASE_IMAGE={{.Runtime}}

FROM ${BASE_IMAGE}

# Install essential tools and SSH server
{{if .IsAlpine}}
RUN apk add --no-cache \
    openssh-server \
    git \
    curl \
    bash \
    sudo \
    {{.ExtraPackages}} \
    && mkdir -p /run/sshd \
    && ssh-keygen -A
{{else}}
RUN apt-get update && apt-get install -y \
    openssh-server \
    git \
    curl \
    sudo \
    {{.ExtraPackages}} \
    && mkdir -p /run/sshd \
    && ssh-keygen -A \
    && rm -rf /var/lib/apt/lists/*
{{end}}

# Create dev user with sudo access
ARG DEV_USER=developer
ARG DEV_UID=1000
ARG DEV_GID=1000

{{if .IsAlpine}}
RUN addgroup -g ${DEV_GID} ${DEV_USER} \
    && adduser -D -u ${DEV_UID} -G ${DEV_USER} -s /bin/bash ${DEV_USER} \
    && echo "${DEV_USER} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/${DEV_USER}
{{else}}
RUN groupadd -g ${DEV_GID} ${DEV_USER} \
    && useradd -m -u ${DEV_UID} -g ${DEV_USER} -s /bin/bash ${DEV_USER} \
    && echo "${DEV_USER} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/${DEV_USER}
{{end}}

# Setup SSH for the dev user
RUN mkdir -p /home/${DEV_USER}/.ssh \
    && chmod 700 /home/${DEV_USER}/.ssh \
    && chown -R ${DEV_USER}:${DEV_USER} /home/${DEV_USER}/.ssh

# Configure SSH daemon
RUN sed -i 's/#PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config \
    && sed -i 's/#PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config \
    && sed -i 's/#PubkeyAuthentication.*/PubkeyAuthentication yes/' /etc/ssh/sshd_config \
    && echo "AllowUsers ${DEV_USER}" >> /etc/ssh/sshd_config

{{if .PackageManagerSetup}}
# Install package manager
{{.PackageManagerSetup}}
{{end}}

{{if .GlobalPackages}}
# Install global packages
{{.GlobalPackages}}
{{end}}

# Set working directory
WORKDIR /home/${DEV_USER}/workspace
RUN chown -R ${DEV_USER}:${DEV_USER} /home/${DEV_USER}

# Switch to dev user for subsequent operations
USER ${DEV_USER}

# Expose SSH port
EXPOSE 22

# Expose debug port
{{if .DebugPort}}
EXPOSE {{.DebugPort}}
{{end}}

# Default command: start SSH daemon
CMD ["sudo", "/usr/sbin/sshd", "-D", "-e"]
`

// TemplateData holds data for Containerfile generation
type TemplateData struct {
	Runtime             string
	IsAlpine            bool
	ExtraPackages       string
	PackageManagerSetup string
	GlobalPackages      string
	DebugPort           int
}

// GenerateContainerfile creates a Containerfile based on config and detection
func (b *Builder) GenerateContainerfile() (string, error) {
	runtime := b.config.Dependencies.Runtime
	if runtime == "" && b.detection != nil {
		runtime = b.detection.Runtime
	}
	if runtime == "" {
		runtime = "node:22-alpine"
	}

	data := TemplateData{
		Runtime:  runtime,
		IsAlpine: strings.Contains(runtime, "alpine"),
	}

	// Set debug port
	if b.detection != nil && b.detection.DebugPort > 0 {
		data.DebugPort = b.detection.DebugPort
	}

	// Handle package manager setup for Node.js
	if b.config.Project.Type == "nodejs" || (b.detection != nil && b.detection.Type == detector.TypeNodeJS) {
		pm := "npm"
		if b.detection != nil && b.detection.PackageManager != "" {
			pm = b.detection.PackageManager
		}

		switch pm {
		case "pnpm":
			data.PackageManagerSetup = "RUN npm install -g pnpm"
		case "yarn":
			data.PackageManagerSetup = "RUN npm install -g yarn"
		case "bun":
			if data.IsAlpine {
				data.PackageManagerSetup = "RUN apk add --no-cache unzip && curl -fsSL https://bun.sh/install | bash"
			} else {
				data.PackageManagerSetup = "RUN curl -fsSL https://bun.sh/install | bash"
			}
		}
	}

	// Add global packages from config
	if len(b.config.Dependencies.Install) > 0 {
		packages := strings.Join(b.config.Dependencies.Install, " ")
		data.GlobalPackages = fmt.Sprintf("RUN npm install -g %s", packages)
	}

	// Parse and execute template
	tmpl, err := template.New("containerfile").Parse(ContainerfileTemplate)
	if err != nil {
		return "", fmt.Errorf("failed to parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("failed to execute template: %w", err)
	}

	return buf.String(), nil
}

// Build builds the container image
func (b *Builder) Build(ctx context.Context) error {
	// Generate Containerfile
	containerfile, err := b.GenerateContainerfile()
	if err != nil {
		return fmt.Errorf("failed to generate Containerfile: %w", err)
	}

	// Create temp directory for build context
	tmpDir, err := os.MkdirTemp("", "devkit-build-")
	if err != nil {
		return fmt.Errorf("failed to create temp directory: %w", err)
	}
	defer os.RemoveAll(tmpDir)

	// Write Containerfile
	containerfilePath := filepath.Join(tmpDir, "Containerfile")
	if err := os.WriteFile(containerfilePath, []byte(containerfile), 0644); err != nil {
		return fmt.Errorf("failed to write Containerfile: %w", err)
	}

	// Build image
	imageName := b.config.ImageName()

	args := []string{
		"build",
		"-t", imageName,
		"-f", containerfilePath,
		tmpDir,
	}

	cmd := exec.CommandContext(ctx, "podman", args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("failed to build image: %w", err)
	}

	return nil
}

// ImageExists checks if the image already exists
func (b *Builder) ImageExists(ctx context.Context) (bool, error) {
	imageName := b.config.ImageName()

	cmd := exec.CommandContext(ctx, "podman", "image", "exists", imageName)
	err := cmd.Run()
	return err == nil, nil
}

// RemoveImage removes the built image
func (b *Builder) RemoveImage(ctx context.Context) error {
	imageName := b.config.ImageName()

	cmd := exec.CommandContext(ctx, "podman", "rmi", imageName)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	return cmd.Run()
}

// GetImageName returns the image name that would be built
func (b *Builder) GetImageName() string {
	return b.config.ImageName()
}

// SaveContainerfile saves the generated Containerfile to a path
func (b *Builder) SaveContainerfile(path string) error {
	containerfile, err := b.GenerateContainerfile()
	if err != nil {
		return err
	}

	return os.WriteFile(path, []byte(containerfile), 0644)
}
