package builder

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/jurajpiar/devkit/internal/config"
	"github.com/jurajpiar/devkit/internal/detector"
)

// Builder handles container image building
type Builder struct {
	config    *config.Config
	detection *detector.DetectionResult
}

// New creates a new Builder
func New(cfg *config.Config, detection *detector.DetectionResult) *Builder {
	return &Builder{
		config:    cfg,
		detection: detection,
	}
}

// ContainerfileTemplate is the template for generating Containerfiles
const ContainerfileTemplate = `# Generated by devkit
ARG BASE_IMAGE={{.Runtime}}

FROM ${BASE_IMAGE}

# Install essential tools, SSH server and client
{{if .IsAlpine}}
RUN apk add --no-cache \
    openssh-server \
    openssh-client \
    git \
    curl \
    bash \
    procps \
    sudo \
    socat \
    {{.SystemPackages}} \
    {{.ExtraPackages}} \
    && mkdir -p /run/sshd \
    && ssh-keygen -A
{{else}}
RUN apt-get update && apt-get install -y \
    openssh-server \
    openssh-client \
    git \
    curl \
    sudo \
    {{.ExtraPackages}} \
    && mkdir -p /run/sshd \
    && ssh-keygen -A \
    && rm -rf /var/lib/apt/lists/*
{{end}}

# Create dev user with sudo access
ARG DEV_USER=developer
ARG DEV_UID=1000
ARG DEV_GID=1000

{{if .IsAlpine}}
# Handle case where GID/UID already exists (common in Alpine)
# Unlock account (-U) to allow SSH pubkey auth
RUN deluser --remove-home $(getent passwd ${DEV_UID} | cut -d: -f1) 2>/dev/null || true \
    && delgroup $(getent group ${DEV_GID} | cut -d: -f1) 2>/dev/null || true \
    && addgroup -g ${DEV_GID} ${DEV_USER} \
    && adduser -D -u ${DEV_UID} -G ${DEV_USER} -s /bin/bash ${DEV_USER} \
    && passwd -u ${DEV_USER} \
    && echo "${DEV_USER} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/${DEV_USER}
{{else}}
# Handle case where GID/UID already exists
# Unlock account to allow SSH pubkey auth
RUN userdel -r $(getent passwd ${DEV_UID} | cut -d: -f1) 2>/dev/null || true \
    && groupdel $(getent group ${DEV_GID} | cut -d: -f1) 2>/dev/null || true \
    && groupadd -g ${DEV_GID} ${DEV_USER} \
    && useradd -m -u ${DEV_UID} -g ${DEV_USER} -s /bin/bash ${DEV_USER} \
    && passwd -u ${DEV_USER} 2>/dev/null || true \
    && echo "${DEV_USER} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/${DEV_USER}
{{end}}

# Create .ssh directory (will be overlayed by tmpfs at runtime for security)
RUN mkdir -p /home/${DEV_USER}/.ssh \
    && chmod 700 /home/${DEV_USER}/.ssh \
    && chown ${DEV_USER}:${DEV_USER} /home/${DEV_USER}/.ssh

# Configure SSH daemon
RUN sed -i 's/#PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config \
    && sed -i 's/#PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config \
    && sed -i 's/#PubkeyAuthentication.*/PubkeyAuthentication yes/' /etc/ssh/sshd_config \
    && echo "AllowUsers ${DEV_USER}" >> /etc/ssh/sshd_config

{{if .PackageManagerSetup}}
# Install package manager
{{.PackageManagerSetup}}
{{end}}

{{if .GlobalPackages}}
# Install global packages
{{.GlobalPackages}}
{{end}}

# Create sshd config (host keys will be generated at startup in /tmp)
RUN mkdir -p /var/empty && chmod 755 /var/empty \
    && echo 'Port 2222' > /etc/ssh/sshd_devkit.conf \
    && echo 'HostKey /tmp/ssh_host_ed25519_key' >> /etc/ssh/sshd_devkit.conf \
    && echo 'HostKey /tmp/ssh_host_rsa_key' >> /etc/ssh/sshd_devkit.conf \
    && echo 'AuthorizedKeysFile /home/developer/.ssh/authorized_keys' >> /etc/ssh/sshd_devkit.conf \
    && echo 'PasswordAuthentication no' >> /etc/ssh/sshd_devkit.conf \
    && echo 'PubkeyAuthentication yes' >> /etc/ssh/sshd_devkit.conf \
    && echo 'PermitRootLogin no' >> /etc/ssh/sshd_devkit.conf \
    && echo 'StrictModes no' >> /etc/ssh/sshd_devkit.conf \
    && echo 'PidFile /tmp/sshd.pid' >> /etc/ssh/sshd_devkit.conf \
    && chmod 644 /etc/ssh/sshd_devkit.conf

# Create entrypoint script that generates host keys and starts sshd
# Note: .ssh, .npm, .cache, .vscode-server are volumes/tmpfs mounted at runtime
RUN echo '#!/bin/sh' > /entrypoint.sh \
    && echo '# Fix ownership of mounted directories (tmpfs/volumes are root-owned initially)' >> /entrypoint.sh \
    && echo 'chown developer:developer /home/developer/.npm 2>/dev/null || true' >> /entrypoint.sh \
    && echo 'chown developer:developer /home/developer/.cache 2>/dev/null || true' >> /entrypoint.sh \
    && echo 'chown developer:developer /home/developer/.ssh 2>/dev/null || true' >> /entrypoint.sh \
    && echo 'chown developer:developer /home/developer/.vscode-server 2>/dev/null || true' >> /entrypoint.sh \
    && echo '# Generate SSH host keys in /tmp' >> /entrypoint.sh \
    && echo 'ssh-keygen -t ed25519 -f /tmp/ssh_host_ed25519_key -N "" -q' >> /entrypoint.sh \
    && echo 'ssh-keygen -t rsa -f /tmp/ssh_host_rsa_key -N "" -q' >> /entrypoint.sh \
    && echo '# Start sshd' >> /entrypoint.sh \
    && echo 'exec /usr/sbin/sshd -D -e -f /etc/ssh/sshd_devkit.conf' >> /entrypoint.sh \
    && chmod +x /entrypoint.sh

# Set working directory (don't chown entire home - causes issues with rootless podman)
WORKDIR /home/${DEV_USER}/workspace
RUN chown ${DEV_USER}:${DEV_USER} /home/${DEV_USER}/workspace

# Expose SSH port
EXPOSE 2222

# Expose debug port
{{if .DebugPort}}
EXPOSE {{.DebugPort}}
{{end}}

# Start sshd via entrypoint (generates keys then runs sshd)
ENTRYPOINT ["/entrypoint.sh"]
`

// TemplateData holds data for Containerfile generation
type TemplateData struct {
	Runtime             string
	IsAlpine            bool
	SystemPackages      string
	ExtraPackages       string
	PackageManagerSetup string
	GlobalPackages      string
	DebugPort           int
}

// GenerateContainerfile creates a Containerfile based on config and detection
func (b *Builder) GenerateContainerfile() (string, error) {
	runtime := b.config.Dependencies.Runtime
	if runtime == "" && b.detection != nil {
		runtime = b.detection.Runtime
	}
	if runtime == "" {
		runtime = "node:22-alpine"
	}

	data := TemplateData{
		Runtime:        runtime,
		IsAlpine:       strings.Contains(runtime, "alpine"),
		SystemPackages: strings.Join(b.config.Dependencies.SystemPackages, " \\\n    "),
	}

	// Set debug port
	if b.detection != nil && b.detection.DebugPort > 0 {
		data.DebugPort = b.detection.DebugPort
	}

	// Handle package manager setup for Node.js
	if b.config.Project.Type == "nodejs" || (b.detection != nil && b.detection.Type == detector.TypeNodeJS) {
		pm := "npm"
		if b.detection != nil && b.detection.PackageManager != "" {
			pm = b.detection.PackageManager
		}

		switch pm {
		case "pnpm":
			data.PackageManagerSetup = "RUN npm install -g pnpm"
		case "yarn":
			data.PackageManagerSetup = "RUN npm install -g yarn"
		case "bun":
			// Install bun and copy to /usr/local/bin for all users (symlink won't work due to /root permissions)
			if data.IsAlpine {
				data.PackageManagerSetup = "RUN apk add --no-cache unzip && curl -fsSL https://bun.sh/install | bash && cp /root/.bun/bin/bun /usr/local/bin/bun && chmod 755 /usr/local/bin/bun"
			} else {
				data.PackageManagerSetup = "RUN curl -fsSL https://bun.sh/install | bash && cp /root/.bun/bin/bun /usr/local/bin/bun && chmod 755 /usr/local/bin/bun"
			}
		}
	}

	// Add global packages from config (filter out package manager to avoid conflicts)
	if len(b.config.Dependencies.Install) > 0 {
		var filteredPackages []string
		for _, pkg := range b.config.Dependencies.Install {
			// Skip if package is the same as the detected package manager
			if b.detection != nil && pkg == b.detection.PackageManager {
				continue
			}
			filteredPackages = append(filteredPackages, pkg)
		}
		if len(filteredPackages) > 0 {
			packages := strings.Join(filteredPackages, " ")
			data.GlobalPackages = fmt.Sprintf("RUN npm install -g %s", packages)
		}
	}

	// Parse and execute template
	tmpl, err := template.New("containerfile").Parse(ContainerfileTemplate)
	if err != nil {
		return "", fmt.Errorf("failed to parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("failed to execute template: %w", err)
	}

	return buf.String(), nil
}

// Build builds the container image
func (b *Builder) Build(ctx context.Context) error {
	// Generate Containerfile
	containerfile, err := b.GenerateContainerfile()
	if err != nil {
		return fmt.Errorf("failed to generate Containerfile: %w", err)
	}

	// Create temp directory for build context
	tmpDir, err := os.MkdirTemp("", "devkit-build-")
	if err != nil {
		return fmt.Errorf("failed to create temp directory: %w", err)
	}
	defer os.RemoveAll(tmpDir)

	// Write Containerfile
	containerfilePath := filepath.Join(tmpDir, "Containerfile")
	if err := os.WriteFile(containerfilePath, []byte(containerfile), 0644); err != nil {
		return fmt.Errorf("failed to write Containerfile: %w", err)
	}

	// Build image
	imageName := b.config.ImageName()

	args := []string{
		"build",
		"-t", imageName,
		"-f", containerfilePath,
		tmpDir,
	}

	cmd := exec.CommandContext(ctx, "podman", args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("failed to build image: %w", err)
	}

	return nil
}

// ImageExists checks if the image already exists
func (b *Builder) ImageExists(ctx context.Context) (bool, error) {
	imageName := b.config.ImageName()

	cmd := exec.CommandContext(ctx, "podman", "image", "exists", imageName)
	err := cmd.Run()
	return err == nil, nil
}

// RemoveImage removes the built image
func (b *Builder) RemoveImage(ctx context.Context) error {
	imageName := b.config.ImageName()

	cmd := exec.CommandContext(ctx, "podman", "rmi", imageName)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	return cmd.Run()
}

// GetImageName returns the image name that would be built
func (b *Builder) GetImageName() string {
	return b.config.ImageName()
}

// SaveContainerfile saves the generated Containerfile to a path
func (b *Builder) SaveContainerfile(path string) error {
	containerfile, err := b.GenerateContainerfile()
	if err != nil {
		return err
	}

	return os.WriteFile(path, []byte(containerfile), 0644)
}
