package lima

import (
	"fmt"
	"os"
	"strings"
	"text/template"

	"github.com/jurajpiar/devkit/internal/runtime"
)

// DefaultImage is the default Linux image for Lima VMs
const DefaultImage = "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-arm64.img"

// LimaConfig represents a Lima VM configuration
type LimaConfig struct {
	VMType       string
	CPUs         int
	MemoryGB     int
	DiskGB       int
	Image        string
	Arch         string
	PortForwards []PortForward
	Mounts       []Mount
	Provision    []Provision
	// Security options
	Plain bool // No GUI, no shared directories
}

// PortForward represents a port forwarding rule
type PortForward struct {
	GuestPort   int
	HostPort    int
	GuestIP     string
	HostIP      string
	Proto       string
	Ignore      bool
}

// Mount represents a mount configuration
type Mount struct {
	Location string
	Writable bool
}

// Provision represents a provisioning script
type Provision struct {
	Mode   string // "system", "user"
	Script string
}

// DefaultLimaConfig returns a default Lima configuration
func DefaultLimaConfig() LimaConfig {
	return LimaConfig{
		VMType:   "vz", // Fast on Apple Silicon
		CPUs:     4,
		MemoryGB: 8,
		DiskGB:   50,
		Image:    DefaultImage,
		Arch:     "aarch64",
		Plain:    false, // Must be false for port forwarding to work
		Provision: []Provision{
			{
				Mode: "system",
				Script: `#!/bin/bash
set -euo pipefail

# Update system
apt-get update

# Install dependencies for rootless containers
apt-get install -y curl ca-certificates uidmap dbus-user-session fuse-overlayfs slirp4netns

# Enable unprivileged user namespaces (required for rootless)
echo "kernel.unprivileged_userns_clone=1" > /etc/sysctl.d/90-rootless.conf
sysctl --system || true

# nerdctl-full includes containerd, buildkit, CNI plugins, rootlesskit, etc.
if ! command -v nerdctl &> /dev/null; then
    echo "Installing nerdctl-full..."
    NERDCTL_VERSION="2.1.3"
    ARCH=$(uname -m)
    if [ "$ARCH" = "aarch64" ]; then
        ARCH="arm64"
    elif [ "$ARCH" = "x86_64" ]; then
        ARCH="amd64"
    fi
    curl -fsSL "https://github.com/containerd/nerdctl/releases/download/v${NERDCTL_VERSION}/nerdctl-full-${NERDCTL_VERSION}-linux-${ARCH}.tar.gz" | tar -xzf - -C /usr/local
fi

# Set up subuid/subgid for the default Lima user
LIMA_USER="${LIMA_CIDATA_USER:-$(id -un 1000 2>/dev/null || echo ubuntu)}"
if ! grep -q "^${LIMA_USER}:" /etc/subuid 2>/dev/null; then
    echo "${LIMA_USER}:100000:65536" >> /etc/subuid
    echo "${LIMA_USER}:100000:65536" >> /etc/subgid
fi
`,
			},
			{
				Mode: "user",
				Script: `#!/bin/bash
set -euo pipefail

# Set up XDG runtime directory for rootless containerd
export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
mkdir -p "$XDG_RUNTIME_DIR"

# Initialize rootless containerd if not already done
if [ ! -f ~/.config/containerd/config.toml ]; then
    echo "Setting up rootless containerd..."
    containerd-rootless-setuptool.sh install || true
fi

# Start rootless containerd if not running
if ! pgrep -u $(id -u) containerd > /dev/null 2>&1; then
    echo "Starting rootless containerd..."
    containerd-rootless-setuptool.sh install || true
fi

# Set up rootless buildkit
if [ ! -f ~/.config/buildkit/buildkitd.toml ]; then
    mkdir -p ~/.config/buildkit
    echo "Starting rootless buildkitd..."
    BUILDKITD_ADDR="unix://$XDG_RUNTIME_DIR/buildkit/buildkitd.sock" \
        containerd-rootless-setuptool.sh install-buildkit || true
fi
`,
			},
		},
		// Security: No mounts by default
		Mounts: []Mount{},
		// Minimal port forwards - Lima guest agent auto-forwards most ports
		// We only explicitly forward SSH to ensure it's always available
		PortForwards: []PortForward{
			{
				GuestPort: 2222, // Container SSH (overridden by config)
				HostPort:  2222,
				HostIP:    "127.0.0.1",
			},
		},
	}
}

// limaTemplate is the Go template for Lima YAML config
const limaTemplate = `# Generated by devkit - do not edit manually
# VM: {{.VMName}}

# VM Type: vz (Virtualization.framework) is fastest on Apple Silicon
vmType: {{.Config.VMType}}

# Resources
cpus: {{.Config.CPUs}}
memory: {{.Config.MemoryGB}}GiB
disk: {{.Config.DiskGB}}GiB

# Base Image
images:
  - location: "{{.Config.Image}}"
    arch: "{{.Config.Arch}}"

# Security: Plain mode disables GUI integration and default mounts
plain: {{.Config.Plain}}

# Containerd for running containers (rootless mode for security)
containerd:
  system: false
  user: true

# SSH port forwarding
ssh:
  localPort: 0  # Auto-assign
  loadDotSSHPubKeys: true

{{if .Config.PortForwards}}
# Port Forwards
portForwards:
{{- range .Config.PortForwards}}
  - guestPort: {{.GuestPort}}
{{- if .HostPort}}
    hostPort: {{.HostPort}}
{{- end}}
{{- if .HostIP}}
    hostIP: "{{.HostIP}}"
{{- end}}
{{- if .GuestIP}}
    guestIP: "{{.GuestIP}}"
{{- end}}
{{- if .Proto}}
    proto: "{{.Proto}}"
{{- end}}
{{- if .Ignore}}
    ignore: true
{{- end}}
{{- end}}
{{end}}

# Security: Explicitly disable all host filesystem mounts
# Without this section, Lima mounts ~ and /tmp/lima by default
mounts: {{if .Config.Mounts}}
{{- range .Config.Mounts}}
  - location: "{{.Location}}"
    writable: {{.Writable}}
{{- end}}
{{- else}}[]{{end}}

# Provisioning Scripts
provision:
{{- range .Config.Provision}}
  - mode: {{.Mode}}
    script: |
{{indent 6 .Script}}
{{- end}}

# Environment variables
env:
  # Disable interactivity
  DEBIAN_FRONTEND: noninteractive
`

// generateConfig generates a Lima VM configuration file
func (m *VMManager) generateConfig(path string, opts runtime.VMOpts) error {
	cfg := DefaultLimaConfig()

	// Apply options
	if opts.CPUs > 0 {
		cfg.CPUs = opts.CPUs
	}
	if opts.MemoryMB > 0 {
		cfg.MemoryGB = opts.MemoryMB / 1024
		if cfg.MemoryGB < 1 {
			cfg.MemoryGB = 1
		}
	}
	if opts.DiskSizeGB > 0 {
		cfg.DiskGB = opts.DiskSizeGB
	}
	if opts.VMType != "" {
		cfg.VMType = opts.VMType
	}
	if opts.Image != "" {
		cfg.Image = opts.Image
	}
	if opts.Arch != "" {
		cfg.Arch = opts.Arch
	}

	// Update SSH port forwarding if specified
	if opts.SSHPort > 0 {
		// Find and update the container SSH port forward
		for i, pf := range cfg.PortForwards {
			if pf.GuestPort == 2222 {
				cfg.PortForwards[i].GuestPort = opts.SSHPort
				cfg.PortForwards[i].HostPort = opts.SSHPort
				break
			}
		}
	}

	// Add additional port forwards
	for _, port := range opts.Ports {
		// Check if port is already configured
		found := false
		for _, pf := range cfg.PortForwards {
			if pf.GuestPort == port {
				found = true
				break
			}
		}
		if !found {
			cfg.PortForwards = append(cfg.PortForwards, PortForward{
				GuestPort: port,
				HostPort:  port,
				HostIP:    "127.0.0.1",
			})
		}
	}

	// Additional provisioning scripts
	for _, script := range opts.Provision {
		cfg.Provision = append(cfg.Provision, Provision{
			Mode:   "system",
			Script: script,
		})
	}

	// Extract VM name from path
	vmName := strings.TrimSuffix(strings.TrimPrefix(path, m.ConfigDir+"/"), ".yaml")

	// Create template
	funcMap := template.FuncMap{
		"indent": func(spaces int, s string) string {
			prefix := strings.Repeat(" ", spaces)
			lines := strings.Split(s, "\n")
			for i, line := range lines {
				if line != "" {
					lines[i] = prefix + line
				}
			}
			return strings.Join(lines, "\n")
		},
	}

	tmpl, err := template.New("lima").Funcs(funcMap).Parse(limaTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse template: %w", err)
	}

	// Create file
	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("failed to create config file: %w", err)
	}
	defer f.Close()

	// Execute template
	data := struct {
		VMName string
		Config LimaConfig
	}{
		VMName: vmName,
		Config: cfg,
	}

	if err := tmpl.Execute(f, data); err != nil {
		return fmt.Errorf("failed to write config: %w", err)
	}

	return nil
}

// GenerateDevkitConfig generates a Lima config optimized for devkit containers
func GenerateDevkitConfig(projectName string, opts runtime.VMOpts) LimaConfig {
	cfg := DefaultLimaConfig()

	// Apply options
	if opts.CPUs > 0 {
		cfg.CPUs = opts.CPUs
	}
	if opts.MemoryMB > 0 {
		cfg.MemoryGB = opts.MemoryMB / 1024
	}
	if opts.DiskSizeGB > 0 {
		cfg.DiskGB = opts.DiskSizeGB
	}
	if opts.VMType != "" {
		cfg.VMType = opts.VMType
	}

	// Lima guest agent auto-forwards ports when services listen on them
	// No need to add explicit port forwards here

	// Add extended provisioning for development
	devProvision := Provision{
		Mode: "system",
		Script: `#!/bin/bash
set -euo pipefail

# Install development essentials
apt-get install -y \
    git \
    curl \
    wget \
    vim \
    openssh-server \
    ca-certificates \
    gnupg \
    build-essential \
    python3 \
    python3-pip

# Configure SSHD for devkit
mkdir -p /etc/ssh/sshd_config.d
cat > /etc/ssh/sshd_config.d/devkit.conf << 'EOF'
Port 2222
PermitRootLogin no
PasswordAuthentication no
PubkeyAuthentication yes
EOF

systemctl restart sshd || true
`,
	}
	cfg.Provision = append(cfg.Provision, devProvision)

	return cfg
}
