package lima

import (
	"fmt"
	"os"
	"strings"
	"text/template"

	"github.com/jurajpiar/devkit/internal/runtime"
)

// DefaultImage is the default Linux image for Lima VMs
const DefaultImage = "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-arm64.img"

// LimaConfig represents a Lima VM configuration
type LimaConfig struct {
	VMType       string
	CPUs         int
	MemoryGB     int
	DiskGB       int
	Image        string
	Arch         string
	PortForwards []PortForward
	Mounts       []Mount
	Provision    []Provision
	// Security options
	Plain bool // No GUI, no shared directories
}

// PortForward represents a port forwarding rule
type PortForward struct {
	GuestPort   int
	HostPort    int
	GuestIP     string
	HostIP      string
	Proto       string
	Ignore      bool
}

// Mount represents a mount configuration
type Mount struct {
	Location string
	Writable bool
}

// Provision represents a provisioning script
type Provision struct {
	Mode   string // "system", "user"
	Script string
}

// DefaultLimaConfig returns a default Lima configuration
func DefaultLimaConfig() LimaConfig {
	return LimaConfig{
		VMType:   "vz", // Fast on Apple Silicon
		CPUs:     4,
		MemoryGB: 8,
		DiskGB:   50,
		Image:    DefaultImage,
		Arch:     "aarch64",
		Plain:    true, // Security: no GUI, minimal sharing
		Provision: []Provision{
			{
				Mode: "system",
				Script: `#!/bin/bash
set -euo pipefail

# Update system
apt-get update

# Install basic tools
apt-get install -y curl ca-certificates

# nerdctl-full includes containerd, buildkit, CNI plugins, etc.
# This is installed by Lima's containerd integration, but we ensure buildkitd is running
if ! command -v buildkitd &> /dev/null; then
    echo "Installing nerdctl-full..."
    NERDCTL_VERSION="2.1.3"
    ARCH=$(uname -m)
    if [ "$ARCH" = "aarch64" ]; then
        ARCH="arm64"
    elif [ "$ARCH" = "x86_64" ]; then
        ARCH="amd64"
    fi
    curl -fsSL "https://github.com/containerd/nerdctl/releases/download/v${NERDCTL_VERSION}/nerdctl-full-${NERDCTL_VERSION}-linux-${ARCH}.tar.gz" | tar -xzf - -C /usr/local
fi

# Ensure containerd is running
systemctl enable --now containerd || true

# Start buildkitd if not running
if ! pgrep buildkitd > /dev/null; then
    echo "Starting buildkitd..."
    nohup buildkitd &>/tmp/buildkitd.log &
    sleep 2
fi

# Create systemd service for buildkitd
cat > /etc/systemd/system/buildkitd.service << 'EOSVC'
[Unit]
Description=BuildKit daemon
After=containerd.service

[Service]
ExecStart=/usr/local/bin/buildkitd
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOSVC

systemctl daemon-reload
systemctl enable --now buildkitd || true
`,
			},
		},
		// Security: No mounts by default
		Mounts: []Mount{},
		// Port forwards for SSH (auto-assigned)
		PortForwards: []PortForward{
			{
				GuestPort: 22,
				HostPort:  0, // Auto-assign
				HostIP:    "127.0.0.1",
			},
		},
	}
}

// limaTemplate is the Go template for Lima YAML config
const limaTemplate = `# Generated by devkit - do not edit manually
# VM: {{.VMName}}

# VM Type: vz (Virtualization.framework) is fastest on Apple Silicon
vmType: {{.Config.VMType}}

# Resources
cpus: {{.Config.CPUs}}
memory: {{.Config.MemoryGB}}GiB
disk: {{.Config.DiskGB}}GiB

# Base Image
images:
  - location: "{{.Config.Image}}"
    arch: "{{.Config.Arch}}"

# Security: Plain mode disables GUI integration and default mounts
plain: {{.Config.Plain}}

# Containerd for running containers
containerd:
  system: true
  user: false

# SSH port forwarding
ssh:
  localPort: 0  # Auto-assign
  loadDotSSHPubKeys: true

{{if .Config.PortForwards}}
# Port Forwards
portForwards:
{{- range .Config.PortForwards}}
  - guestPort: {{.GuestPort}}
{{- if .HostPort}}
    hostPort: {{.HostPort}}
{{- end}}
{{- if .HostIP}}
    hostIP: "{{.HostIP}}"
{{- end}}
{{- if .GuestIP}}
    guestIP: "{{.GuestIP}}"
{{- end}}
{{- if .Proto}}
    proto: "{{.Proto}}"
{{- end}}
{{- if .Ignore}}
    ignore: true
{{- end}}
{{- end}}
{{end}}

{{if .Config.Mounts}}
# Mounts
mounts:
{{- range .Config.Mounts}}
  - location: "{{.Location}}"
    writable: {{.Writable}}
{{- end}}
{{end}}

# Provisioning Scripts
provision:
{{- range .Config.Provision}}
  - mode: {{.Mode}}
    script: |
{{indent 6 .Script}}
{{- end}}

# Environment variables
env:
  # Disable interactivity
  DEBIAN_FRONTEND: noninteractive
`

// generateConfig generates a Lima VM configuration file
func (m *VMManager) generateConfig(path string, opts runtime.VMOpts) error {
	cfg := DefaultLimaConfig()

	// Apply options
	if opts.CPUs > 0 {
		cfg.CPUs = opts.CPUs
	}
	if opts.MemoryMB > 0 {
		cfg.MemoryGB = opts.MemoryMB / 1024
		if cfg.MemoryGB < 1 {
			cfg.MemoryGB = 1
		}
	}
	if opts.DiskSizeGB > 0 {
		cfg.DiskGB = opts.DiskSizeGB
	}
	if opts.VMType != "" {
		cfg.VMType = opts.VMType
	}
	if opts.Image != "" {
		cfg.Image = opts.Image
	}
	if opts.Arch != "" {
		cfg.Arch = opts.Arch
	}

	// Additional provisioning scripts
	for _, script := range opts.Provision {
		cfg.Provision = append(cfg.Provision, Provision{
			Mode:   "system",
			Script: script,
		})
	}

	// Extract VM name from path
	vmName := strings.TrimSuffix(strings.TrimPrefix(path, m.ConfigDir+"/"), ".yaml")

	// Create template
	funcMap := template.FuncMap{
		"indent": func(spaces int, s string) string {
			prefix := strings.Repeat(" ", spaces)
			lines := strings.Split(s, "\n")
			for i, line := range lines {
				if line != "" {
					lines[i] = prefix + line
				}
			}
			return strings.Join(lines, "\n")
		},
	}

	tmpl, err := template.New("lima").Funcs(funcMap).Parse(limaTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse template: %w", err)
	}

	// Create file
	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("failed to create config file: %w", err)
	}
	defer f.Close()

	// Execute template
	data := struct {
		VMName string
		Config LimaConfig
	}{
		VMName: vmName,
		Config: cfg,
	}

	if err := tmpl.Execute(f, data); err != nil {
		return fmt.Errorf("failed to write config: %w", err)
	}

	return nil
}

// GenerateDevkitConfig generates a Lima config optimized for devkit containers
func GenerateDevkitConfig(projectName string, opts runtime.VMOpts) LimaConfig {
	cfg := DefaultLimaConfig()

	// Apply options
	if opts.CPUs > 0 {
		cfg.CPUs = opts.CPUs
	}
	if opts.MemoryMB > 0 {
		cfg.MemoryGB = opts.MemoryMB / 1024
	}
	if opts.DiskSizeGB > 0 {
		cfg.DiskGB = opts.DiskSizeGB
	}
	if opts.VMType != "" {
		cfg.VMType = opts.VMType
	}

	// Add port forwards for SSH (2222) and typical dev ports
	commonPorts := []int{2222, 3000, 3001, 5173, 8080, 8000, 9229}
	for _, port := range commonPorts {
		cfg.PortForwards = append(cfg.PortForwards, PortForward{
			GuestPort: port,
			HostPort:  port,
			HostIP:    "127.0.0.1",
		})
	}

	// Add extended provisioning for development
	devProvision := Provision{
		Mode: "system",
		Script: `#!/bin/bash
set -euo pipefail

# Install development essentials
apt-get install -y \
    git \
    curl \
    wget \
    vim \
    openssh-server \
    ca-certificates \
    gnupg \
    build-essential \
    python3 \
    python3-pip

# Configure SSHD for devkit
mkdir -p /etc/ssh/sshd_config.d
cat > /etc/ssh/sshd_config.d/devkit.conf << 'EOF'
Port 2222
PermitRootLogin no
PasswordAuthentication no
PubkeyAuthentication yes
EOF

systemctl restart sshd || true
`,
	}
	cfg.Provision = append(cfg.Provision, devProvision)

	return cfg
}
